version: '3.8'
services:
  fdroid:
    build:
      context: ./fdroid-server
    depends_on:
      android-sdk:
        condition: service_healthy
    volumes:
      - ./fdroid-server/fdroid:/fdroid
      - shared-data:/opt/android-sdk
    environment:
      - ANDROID_HOME=/opt/android-sdk
    healthcheck:
      test: ["CMD", "test", "-f", "/fdroid/repo/index-v1.jar"]
      interval: 10s
      retries: 10
      start_period: 10s
    container_name: fdroid-server

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.config:/etc/nginx/nginx.conf
      - ./fdroid-server/fdroid:/usr/share/nginx/html/fdroid
    ports:
      - "8080:80"
    healthcheck:
      test: ["CMD", "test", "-f", "/usr/share/nginx/html/fdroid/index-v1.jar"]
      interval: 10s
      retries: 10
      start_period: 10s
    container_name: fdroid-nginx

  android-sdk:
    image: thyrlian/android-sdk
    container_name: android-sdk
    volumes:
      - shared-data:/opt/android-sdk
      - ./android-init.sh:/android-init.sh
    environment:
      - ANDROID_HOME=/opt/android-sdk
      - ANDROID_SDK_ROOT=/opt/android-sdk
    command: ["/bin/bash", "/android-init.sh"]
    tty: true
    healthcheck:
      test: ["CMD", "test", "-f", "/opt/android-sdk/platform-tools/adb"]
      interval: 10s
      retries: 10
      start_period: 10s

volumes:
  shared-data:
